### ISSUE TITLE
app crashing randomly after browsing for a while

### ISSUE THREAD

**Issue by killoid** [saket/Dank#5]
i am using this awesome app on my samsung galaxy note 3 SM-N9005 running unofficial LOS16. i know you are not working anymore on this app. but it would be really great if you at least fix the crash i am facing when i am browsing reddit. i am attaching a log file below. again thanks for your great work!

[2019-01-04-19-58-35.txt](https://github.com/saket/Dank/files/2727245/2019-01-04-19-58-35.txt)

**Comment by Tunous** [comment]
I've fixed this issue and few other in [my fork](https://github.com/Tunous/Dank). I do not have any signing keys though, so you can only download debug version (latest available [here](https://7-162332333-gh.circle-artifacts.com/0/outputs/apk/debug/app-debug.apk)) or compile it yourself.

**Comment by killoid** [comment]
@Tunous i am running the debug version & it's all good! i am gonna post further issues in your fork from now on. hoping to see more improvements & implementations from you! thanks!
